#Listener configurations
"http":
   "host": "0.0.0.0"
   "port": "8092"
   "basepath": "/"
   "listener":
      "config": "sitecore-sapi-listener-config"
      "timeout": "30000"
# api details
"application":
  "name":  "sitecore-integration"
  "version"     : "1"
  "instanceName": "dch-asset-processing-papi"
  "environment": "dev"
  "status": "running"
#mongo sapi config  
"mongoconfig":
   "username": "shani"
   "password": "shani"
   "host": "localhost"
   "port": "8081"
   "basePath": "/api/"
   "protocol": "HTTP"
   "timeout": "300000"