#Listener configurations
"http":
   "host": "0.0.0.0"
   "port": "8093"
   "basepath": "/"
   "config": "asset-processing-papi-2-httpListenerConfig"
   "timeout": "30000"
#api details
"application":
  "name":  "dch-asset-processing-papi"
  "version"     : "1"
  "instanceName": "dch-asset-processing-papi"
  "environment": "dev"
  "status": "running"
#mongo sapi config  
"mongoconfig":
   "username": "shani"
   "password": "shani"
   "host": "localhost"
   "port": "8084"
   "basePath": "/api/"
   "protocol": "HTTP"
   "timeout": "300000"
   "postpath": "mAssets"
   "exppath": "expAsset"
   
#sitecore sapi config  
"sitecoreconfig":
   "username": "shani"
   "password": "shani"
   "host": "localhost"
   "port": "8082"
   "basePath": "/api/"
   "protocol": "HTTP"
   "timeout": "10000000"
#update-url-papi
"updatepapiconfig":
   "host": "localhost"
   "port": "8085"
   "basePath": "/api/"
   "protocol": "HTTP"
   "timeout": "10000000"
   "updatepath": "uAssets"  
#S3
"S3":
  "AccessKey": "![jZLkpJkWbdipvj5cK/glmAqG3ROJe/DO]"
  "SecretKey": "![jCy0ShjvrqBZ1gI6igjn7t3J0NY83bcJ9+E7MisgJIseitdaUApaktHg5G0b3+8J]"
  "bucket": "sitecore"
  "region": "us-east-1"
#Scheduler
"Scheduler":
  "frequency": "1"
#secure properties
"secure":
  "key": "mulesoft" 
#DRM rights profile href url
"drm":
  "url": "http://sitecore-integration.us-e2.cloudhub.io/hrefentities/1861637"  
#createdby url
"createdby":
  "url": "http://sitecore-integration.us-e2.cloudhub.io/createdby/6"
#modifiedby url
"modifiedby":
  "url": "http://sitecore-integration.us-e2.cloudhub.io/modifiedby/120941"  
#process scheduler
"pscheduler": 
  "frequency": "1"
#delete scheduler
"dscheduler": 
  "frequency": "1"
    
  
  
  
  
         
              
                            
         
              
                            